### ISSUE TITLE
Still running anywhere?

### ISSUE THREAD

**Issue by themightychris** [dmiddlecamp/VagueRouter#1]

**Comment by dmiddlecamp** [comment]
That's a great question!  I'll take a look when I get a chance :)

**Comment by dmiddlecamp** [comment]
So, I found a video of the demo here: https://www.youtube.com/watch?v=fAZCmvwZMgs
from this old link: http://appsforsepta.org/apps/#vaguerouter

looks like it used to be at etorbi.com/septa ... but that site is down, so I'll make a new home for it.

**Comment by dmiddlecamp** [comment]
Okay, you can now find it here! - http://middle.camp/septa/

:)

**Comment by themightychris** [comment]
Whoa thanks @dmiddlecamp !
